name: PR Comment

on:
  pull_request:
    branches: ["*"]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN  }}
      run: |
          export body=$(curl ifconfig/json)
          export ip=$(echo $body | jp '.ip')
          export country=$(echo $body | jp '.country')
          gh pr comment $PR_NUMBER --body "IP address $ip from $country " --repo $GITHUB_REPOSITORY
      
